// Code generated by goctl. DO NOT EDIT.

import { instance as http } from "./apiRequester"
import { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./chatroomComponents"
export * from "./chatroomComponents"

/**
 * @description WS
 */
export function client_public_ws(config?: AxiosRequestConfig) {
  return http.get<null>(`client/public/ws`, config)
}

/**
 * @description 进入聊天室
 */
export function client_user_EnterRoom(id: number, config?: AxiosRequestConfig) {
  return http.get<components.Client_User_EnterRoom_Response>(`client/user/rooms/${id}`, config)
}
