// Code generated by goctl. DO NOT EDIT.

export interface Manager_Public_GetSignUpCaptcha_Request {
}

export interface Manager_Public_GetSignUpCaptcha_Response {
}

export interface Manager_Public_CheckSignUpCaptcha_Request {
}

export interface Manager_Public_CheckSignUpCaptcha_Response {
}

export interface Manager_Public_SignUpAccount_Request {
  account: string // 账号
  password: string // 密码（前端加密后提交）
  captcha_code: string // 图形验证码
}

export interface Manager_Public_SignUpAccount_Response {
  token: string
}

export interface Manager_Public_GetSignInCaptcha_Request {
}

export interface Manager_Public_GetSignInCaptcha_Response {
}

export interface Manager_Public_CheckSignInCaptcha_Request {
}

export interface Manager_Public_CheckSignInCaptcha_Response {
}

export interface Manager_Public_SignInAccount_Request {
  account: string // 账号
  password: string // 密码（前端加密后提交）
  captcha_code: string // 图形验证码
}

export interface Manager_Public_SignInAccount_Response {
  token: string
}

export interface Manager_Admin_SignOut_Request {
}

export interface Manager_Admin_SignOut_Response {
}

export interface Manager_Admin_EditPassword_Request {
  original_password: string // 原始密码（前端加密后提交）
  new_password: string // 新的密码（前端加密后提交）
}

export interface Manager_Admin_EditPassword_Response {
}

export interface Manager_Admin_GetAdminList_Request {
}
export interface Manager_Admin_GetAdminList_RequestParams {
  page: number // 当前页码
  per_page: number // 每页条目
  order_column: string // 排序字段
  order_type: string // 排序类型，asc、desc
  search_account_like: string // 账号
}

export interface Manager_Admin_GetAdminList_Response {
  total: number
  items: Array<Manager_Admin_GetAdminList_Response_Item>
}

export interface Manager_Admin_GetAdminList_Response_Item {
  id: number // 管理员 ID
  name: string // 名称
  account: string // 账号
  created_at: number // 创建时间
  last_signin_at: number // 上次登录时间
}

export interface Manager_Admin_GetAdminInfo_Request {
}
export interface Manager_Admin_GetAdminInfo_RequestParams {
}

export interface Manager_Admin_GetAdminInfo_Response {
  id: number // 管理员 ID
  name: string // 名称
  account: string // 账号
  created_at: number // 创建时间
  last_signin_at: number // 上次登录时间
}

