// Code generated by goctl. DO NOT EDIT.

import { instance as http } from "./apiRequester"
import { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./adminComponents"
export * from "./adminComponents"

/**
 * @description 获取注册图形验证码
 */
export function manager_public_getSignUpCaptcha(config?: AxiosRequestConfig) {
  return http.get<components.Manager_Public_GetSignUpCaptcha_Response>(`manager/public/sign-up/captcha`, config)
}

/**
 * @description 校验注册图形验证码
 */
export function manager_public_checkSignUpCaptcha(config?: AxiosRequestConfig) {
  return http.patch<components.Manager_Public_CheckSignUpCaptcha_Response>(`manager/public/sign-up/check-captcha`, config)
}

/**
 * @description 账号注册
 * @param req
 */
export function manager_public_signUpAccount(req: components.Manager_Public_SignUpAccount_Request, config?: AxiosRequestConfig) {
  return http.post<components.Manager_Public_SignUpAccount_Response>(`manager/public/sign-up/account`, req, config)
}

/**
 * @description 获取登录图形验证码
 */
export function manager_public_getSignInCaptcha(config?: AxiosRequestConfig) {
  return http.get<components.Manager_Public_GetSignInCaptcha_Response>(`manager/public/sign-in/captcha`, config)
}

/**
 * @description 校验登录图形验证码
 */
export function manager_public_checkSignInCaptcha(config?: AxiosRequestConfig) {
  return http.post<components.Manager_Public_CheckSignInCaptcha_Response>(`manager/public/sign-in/check-captcha`, config)
}

/**
 * @description 账号登录
 * @param req
 */
export function manager_public_signInAccount(req: components.Manager_Public_SignInAccount_Request, config?: AxiosRequestConfig) {
  return http.post<components.Manager_Public_SignInAccount_Response>(`manager/public/sign-in/account`, req, config)
}

/**
 * @description 安全退出
 */
export function manager_admin_signOut(config?: AxiosRequestConfig) {
  return http.post<components.Manager_Admin_SignOut_Response>(`manager/admin/sign-out`, config)
}

/**
 * @description 修改密码
 * @param req
 */
export function manager_admin_editPassword(req: components.Manager_Admin_EditPassword_Request, config?: AxiosRequestConfig) {
  return http.put<components.Manager_Admin_EditPassword_Response>(`manager/admin/password`, req, config)
}

/**
 * @description 获取管理员列表
 * @param query
 */
export function manager_admin_getAdminList(query: components.Manager_Admin_GetAdminList_RequestParams, config?: AxiosRequestConfig) {
  return http.get<components.Manager_Admin_GetAdminList_Response>(`manager/admin/users` + `?` + qs.stringify(query), config)
}

/**
 * @description 获取管理员详情
 */
export function manager_admin_getAdminInfo(id: number, config?: AxiosRequestConfig) {
  return http.get<components.Manager_Admin_GetAdminInfo_Response>(`manager/admin/users/${id}`, config)
}
