// Code generated by goctl. DO NOT EDIT.

import axios, { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./chatroomComponents"
export * from "./chatroomComponents"

// https://axios-http.com/zh/docs/intro
export const http = axios.create();

/**
 * @description Demo
 */
export function manager_admin_demo(config?: AxiosRequestConfig) {
  return http.post<components.Manager_Admin_Demo_Response>(`manager/admin/demo`, config)
}
