// Code generated by goctl. DO NOT EDIT.

import { instance as http } from "./apiRequester"
import { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./chatroomComponents"
export * from "./chatroomComponents"

/**
 * @description Demo
 */
export function manager_admin_demo(config?: AxiosRequestConfig) {
  return http.post<components.Manager_Admin_Demo_Response>(`manager/admin/demo`, config)
}
