// Code generated by goctl. DO NOT EDIT.

import { instance as http } from "./apiRequester"
import { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./userComponents"
export * from "./userComponents"

/**
 * @description 获取用户列表
 * @param query
 */
export function manager_admin_getUserList(query: components.Manager_Admin_GetUserList_RequestParams, config?: AxiosRequestConfig) {
  return http.get<components.Manager_Admin_GetUserList_Response>(`manager/admin/users` + `?` + qs.stringify(query), config)
}

/**
 * @description 获取用户详情
 */
export function manager_admin_getUserInfo(id: number, config?: AxiosRequestConfig) {
  return http.get<components.Manager_Admin_GetUserInfo_Response>(`manager/admin/users/${id}`, config)
}
