// Code generated by goctl. DO NOT EDIT.

export interface Manager_Admin_GetUserList_Request {
}
export interface Manager_Admin_GetUserList_RequestParams {
  page: number // 当前页码
  per_page: number // 每页条目
  order_column: string // 排序字段
  order_type: string // 排序类型，asc、desc
  search_account_like: string // 账号
}

export interface Manager_Admin_GetUserList_Response {
  total: number
  items: Array<Manager_Admin_GetUserList_Response_Item>
}

export interface Manager_Admin_GetUserList_Response_Item {
  id: number // 用户 ID
  name: string // 名称
  account: string // 账号
  created_at: number // 创建时间
  last_signin_at: number // 上次登录时间
}

export interface Manager_Admin_GetUserInfo_Request {
}
export interface Manager_Admin_GetUserInfo_RequestParams {
}

export interface Manager_Admin_GetUserInfo_Response {
  id: number // 用户 ID
  name: string // 名称
  account: string // 账号
  created_at: number // 创建时间
  last_signin_at: number // 上次登录时间
}

